object Versions {
    const val gradlePlugin = "7.1.0"
    const val navigationArgs = "2.4.1"
    const val kotlinGradlePlugin = "1.6.10"
    const val appCompat = "1.4.1"
    const val constraintLayout = "2.1.3"
    const val coreKtx = "1.7.0"
    const val legacySupport = "1.0.0"
    const val customTabs = "1.4.0"
    const val nav_version = "2.4.0"
    const val sdp = "1.0.6"
    const val lifecycle_extensions = "1.1.1"
    const val dataBindingCompiler = "3.1.4"
    const val retrofit = "2.9.0"
    const val kotlinx_serialization_converter = "0.8.0"
    const val gson = "2.8.7"
    const val okhttp3 = "5.0.0-alpha.2"
    const val glide_version = "4.12.0"
    const val hilt_version = "2.38.1"
}